export const vendors = [
  {
    id: "2betties",
    name: "2Betties",
    location: "Baltimore, MD",
    address: "1215 E. Fort Drive #004, Baltimore, MD 21230",
    website: "https://2betties.com",
    businessType: "Corporation",
    revenue: "Early Stage ($500K-$1M/yr)",
    employees: "2-10",
    certifications: ["Woman-Owned Business"],
    categories: ["Snacks"],
    deliverySchedule: "Mon to Fri",
    minOrderQuantity: "2 cases",
    logo: "/vendors/2betties/logo.jpeg",
    about: "2Betties makes better-for-you snacking easy and joyful. Certified Gluten-Free, Non-GMO, and Women-Owned.",
    owned: "Owned by: Nancy Becker and Bridget Greaney",
    story: "2Betties started in a college dorm room — co-founders on a mission to raise the bar one better bite at a time.",
    goals: ["Retail Product"],
    orderRules: {
      minCases: 2,
      unitsPerCase: 6,
      minUnits: 12,
      mixAndMatch: true,
      mixAndMatchNote: "Minimum 2 cases (12 units) required. Flavors are interchangeable to meet the minimum."
    },
    products: [
      {
        id: "16820",
        name: "Bites (2-pack) - Chocolate Chip",
        upc: "850004178164",
        size: "1.4 oz",
        wholesaleUnitPrice: 1.89,
        msrp: 2.99,
        casePack: 6,
        unitsPerCase: 6,
        wholesaleCasePrice: 68.20,
        caseMinimum: 1,
        storage: "Dry/Ambient: 7-12 months",
        allergens: ["Dairy-Free", "Gluten-Free", "Peanut-Free", "Soy-Free", "Egg-Free"],
        dietary: ["Paleo", "Low-Fat", "Low-Carb", "Low-Sugar", "Low-Sodium"],
        category: "Snacks",
        image: "/vendors/2betties/chocolate-chip.png"
      },
      {
        id: "16821",
        name: "Bites (2-pack) - Chocolate Chunk",
        upc: "861513000433",
        size: "1.4 oz",
        wholesaleUnitPrice: 1.89,
        msrp: 2.99,
        casePack: 6,
        unitsPerCase: 6,
        wholesaleCasePrice: 68.20,
        caseMinimum: 1,
        storage: "Dry/Ambient: 7-12 months",
        allergens: ["Dairy-Free", "Gluten-Free", "Peanut-Free", "Soy-Free", "Egg-Free"],
        dietary: ["Paleo", "Low-Fat", "Low-Carb", "Low-Sugar", "Low-Sodium"],
        category: "Snacks",
        image: "/vendors/2betties/chocolate-chunk.png"
      },
      {
        id: "16822",
        name: "Bites (2-pack) - Lemon",
        upc: "850004178201",
        size: "1.4 oz",
        wholesaleUnitPrice: 1.89,
        msrp: 2.99,
        casePack: 6,
        unitsPerCase: 6,
        wholesaleCasePrice: 68.20,
        caseMinimum: 1,
        storage: "Dry/Ambient: 7-12 months",
        allergens: ["Dairy-Free", "Gluten-Free", "Peanut-Free", "Soy-Free", "Egg-Free"],
        dietary: ["Paleo", "Low-Fat", "Low-Carb", "Low-Sugar", "Low-Sodium"],
        category: "Snacks",
        image: "/products/2betties/2betties-lemon.png"
      },
      {
        id: "16823",
        name: "Bites (2-pack) - Maple Cinnamon",
        upc: "861513000419",
        size: "1.4 oz",
        wholesaleUnitPrice: 1.89,
        msrp: 2.99,
        casePack: 6,
        unitsPerCase: 6,
        wholesaleCasePrice: 68.20,
        caseMinimum: 1,
        storage: "Dry/Ambient: 7-12 months",
        allergens: ["Dairy-Free", "Gluten-Free", "Peanut-Free", "Soy-Free", "Egg-Free"],
        dietary: ["Paleo", "Low-Fat", "Low-Carb", "Low-Sugar", "Low-Sodium"],
        category: "Snacks",
        image: "/vendors/2betties/maple-cinnamon.png"
      },
      {
        id: "16824",
        name: "Bites (2-pack) - Sweet Almond",
        upc: "850004178010",
        size: "1.4 oz",
        wholesaleUnitPrice: 1.89,
        msrp: 2.99,
        casePack: 6,
        unitsPerCase: 6,
        wholesaleCasePrice: 68.20,
        caseMinimum: 1,
        storage: "Dry/Ambient: 7-12 months",
        allergens: ["Dairy-Free", "Gluten-Free", "Peanut-Free", "Soy-Free", "Egg-Free"],
        dietary: ["Paleo", "Low-Fat", "Low-Carb", "Low-Sugar", "Low-Sodium"],
        category: "Snacks",
        image: "/vendors/2betties/sweet-almond.png"
      }
    ]
  },
  {
    id: "ethiopian-delights",
    name: "Ethiopian Delights",
    location: "Silver Spring, MD",
    address: "13208 Bellevue Street, Silver Spring, MD 20904",
    website: "http://www.ethiodelights.com",
    businessType: "Partnership",
    revenue: "Start-Up (<$250K/yr)",
    employees: "2-10",
    certifications: ["Woman-owned Business", "Minority-owned Business"],
    categories: ["Dry Goods"],
    deliveryArea: "Washington D.C., Baltimore, Culpeper-Charlottesville",
    deliverySchedule: "Self-distribute",
    minOrderQuantity: "1 case (12 units)",
    production: "Takoma Park Silver Spring Community Kitchen, 310 Tulip Ave, Takoma Park, MD",
    seasonalOfferings: "Farmers Markets, Holiday Markets, online",
    growthGoals: "At Ethiopian Delights, we are storytellers of Ethiopian culture through flavor. Our mission is to introduce authentic, high-quality Ethiopian-inspired cuisine to the D.C. metropolitan area.",
    logo: "/vendors/ethiopian-delights/logo.png",
    about: "Ethiopian Delights brings the rich and diverse flavors of Ethiopian cuisine to a global audience. We offer instant, ready-to-eat meals inspired by traditional Ethiopian dishes. All of our products are gluten-free and vegan.",
    story: "Beza Bisrat, MBA, is the founder of Ethiopian Delights. As an Ethiopian American, she felt disconnected from her culture when her career took her away from her home in Washington D.C. She found solace in cooking and was inspired to make authentic Ethiopian packaged food more accessible and visible.",
    owned: "Owned by: Beza Bisrat",
    goals: ["Retail Product"],
    socialLinks: { instagram: true, facebook: true },
    orderRules: {
      minCases: 1,
      unitsPerCase: 12,
      minUnits: 12,
      mixAndMatch: true,
      mixAndMatchNote: "Minimum 1 case (12 units) required. Flavors are interchangeable to meet the minimum."
    },
    products: [
      {
        id: "10616",
        name: "Spicy Red Lentil Stew",
        upc: "860012111305",
        size: "3.5 oz",
        wholesaleUnitPrice: 6.29,
        msrp: 8.99,
        casePack: 12,
        unitsPerCase: 12,
        wholesaleCasePrice: 75.48,
        caseMinimum: 1,
        storage: "1 year shelf life, no need for refrigeration",
        allergens: ["Dairy-Free", "Peanut-Free", "Tree Nut-Free", "Seafood-Free", "Sesame-Free", "Egg-Free"],
        dietary: ["Vegan", "Vegetarian", "Low-Sugar"],
        cuisine: "African",
        category: "Dry Goods",
        image: "/vendors/ethiopian-delights/spicy-red-lentil-stew.png"
      },
      {
        id: "10617",
        name: "Mild Split Pea Stew",
        upc: "860012111312",
        size: "3.5 oz",
        wholesaleUnitPrice: 6.29,
        msrp: 8.99,
        casePack: 12,
        unitsPerCase: 12,
        wholesaleCasePrice: 75.48,
        caseMinimum: 1,
        storage: "1 year shelf life, no need for refrigeration",
        allergens: ["Dairy-Free", "Peanut-Free", "Tree Nut-Free", "Seafood-Free", "Sesame-Free", "Egg-Free"],
        dietary: ["Vegan", "Vegetarian", "Low-Sugar"],
        cuisine: "African",
        category: "Dry Goods",
        image: "/vendors/ethiopian-delights/mild-split-pea-stew.png"
      }
    ]
  },
  {
    id: "open-seas-coffee-roasters",
    name: "Open Seas Coffee Roasters",
    location: "Stevensville, MD",
    address: "100 Pier Ave Unit A, Stevensville, MD 21666",
    website: "http://www.openseascoffee.com",
    businessType: "Sole Proprietorship",
    revenue: "Early Stage ($500K-$1M/yr)",
    employees: "2-10",
    insurance: "General Liability Insurance, Auto Coverage, Workers' Compensation",
    healthClearance: "Yes",
    certifications: [],
    categories: ["Beverages"],
    deliveryArea: "Anne Arundel, Baltimore County, Wicomico and Worcester. Free Shipping on 4 cases. Delivery fee $13.25",
    deliverySchedule: "Wed to Fri / Delivery every Fri",
    minOrderQuantity: "2 case minimum",
    production: "Open Seas Coffee Roasters, 100 Pier Ave, Stevensville, MD 21666",
    seasonalOfferings: null,
    growthGoals: "We're stoked about our canned cold brew and are in talks with our co-packer about launching additional canned products in the near future!",
    logo: "/vendors/open-seas-coffee-roasters/logo.png",
    owned: "Owned by: Bryce Roszell",
    about: "Open Seas Coffee Roasters is a wholesale roastery located in Stevensville, MD. We define ourselves by our three core values: Intentional, Interconnected, and Quality Driven. You can find our coffee served at many locations along the East Coast, and across the country!",
    story: "Here at Open Seas Coffee we define ourselves by our three core values: intentional, interconnected, and quality driven. We were dreamt up in 2014 by Bryce & Erica Roszell while living in Laos picking coffee cherries with friends. After returning to the States in 2015 Bryce opened Open Seas Coffee. We have the pleasure of roasting some truly brilliant coffees delivered to us from origin pre-loaded with potential.",
    goals: ["Retail Product", "Back-of-House Product"],
    socialLinks: { instagram: true, facebook: true },
    orderRules: {
      minCases: 2,
      unitsPerCase: 12,
      minUnits: 24,
      mixAndMatch: false,
      mixAndMatchNote: "Minimum 2 cases (24 units) required."
    },
    products: [
      {
        id: "16523",
        name: "Cold Brew, Can",
        upc: "12345678905",
        size: "12 oz",
        wholesaleUnitPrice: 3.25,
        msrp: 5.25,
        casePack: 12,
        unitsPerCase: 12,
        wholesaleCasePrice: 39.00,
        caseMinimum: 2,
        storage: "Dry/Ambient: 7-12 months, Cold: 7-12 months, Warm: 7-12 months",
        allergens: ["Dairy-Free", "Gluten-Free", "Peanut-Free", "Tree Nut-Free", "Seafood-Free", "Sesame-Free", "Soy-Free", "Casein-Free", "Egg-Free"],
        dietary: ["Vegan", "Vegetarian", "Organic / Naturally Grown", "Paleo", "Keto-Friendly", "Low-Fat", "Low-Carb", "Low-Sugar", "Low-Sodium"],
        cuisine: null,
        category: "Beverages",
        breadcrumb: "Beverages / Coffee",
        image: "/vendors/open-seas-coffee-roasters/cold-brew-can.png"
      },
      {
        id: "16524",
        name: "Shipping Fee",
        upc: null,
        size: null,
        wholesaleUnitPrice: 13.25,
        msrp: null,
        casePack: null,
        unitsPerCase: null,
        wholesaleCasePrice: null,
        caseMinimum: null,
        storage: null,
        allergens: [],
        dietary: [],
        category: "Beverages",
        image: null,
        isShippingFee: true
      }
    ]
  }
]
